//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalALPR
    {
        public int AdditionalALPRId { get; set; }
        public string ALPRIP { get; set; }
        public Nullable<bool> LoopEnabled { get; set; }
        public string GateName { get; set; }
        public Nullable<bool> AIEnabled { get; set; }
        public Nullable<bool> LaserTriggerEnabled { get; set; }
    }
}
