//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string admin_id { get; set; }
        public string admin_password { get; set; }
        public string admin_first { get; set; }
        public string admin_middle { get; set; }
        public string admin_last { get; set; }
        public string admin_type { get; set; }
        public string admin_phone { get; set; }
        public Nullable<byte> gate_no { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
