//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        public int camera_id { get; set; }
        public string camera_role { get; set; }
        public Nullable<int> gate_id { get; set; }
    
        public virtual Gate Gate { get; set; }
    }
}
