//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int visitor_id { get; set; }
        public int visitor_vehicle_license_plate { get; set; }
        public System.DateTime visitor_entry_date { get; set; }
        public System.DateTime visitor_entry_time { get; set; }
        public int visitor_entry_gate { get; set; }
        public Nullable<System.DateTime> visitor_exit_date { get; set; }
        public Nullable<System.DateTime> visitor_exit_time { get; set; }
        public Nullable<int> visitor_exit_gate { get; set; }
        public string visitor_license_prefix { get; set; }
        public string visitor_license_number { get; set; }
        public string visitor_license_number_arabic { get; set; }
        public string visitor_license_region { get; set; }
        public string visitor_license_country { get; set; }
        public string visitor_license_back_color { get; set; }
        public string visitor_license_fore_color { get; set; }
        public string visitor_license_type { get; set; }
        public Nullable<int> visitor_license_accuracy { get; set; }
        public string visitor_guard_id { get; set; }
        public string visitor_alpr_recording { get; set; }
        public string visitor_driver_recording { get; set; }
        public string visitor_scene_recording { get; set; }
        public string visitor_iviss_recording { get; set; }
        public string visitor_access_status { get; set; }
        public string visitor_access_gate { get; set; }
        public Nullable<byte> uploaded { get; set; }
        public string visitor_authorization { get; set; }
        public string gate_no { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<byte> is_default { get; set; }
        public Nullable<byte> is_primary { get; set; }
    }
}
