//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.Guards = new HashSet<Guard>();
            this.Visitors = new HashSet<Visitor>();
            this.Organizations = new HashSet<Organization>();
        }
    
        public int facility_id { get; set; }
        public string facility_name { get; set; }
        public string facility_city { get; set; }
        public string facility_region { get; set; }
        public string facility_country { get; set; }
    
        public virtual ICollection<Guard> Guards { get; set; }
        public virtual ICollection<Visitor> Visitors { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
