//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gate
    {
        public Gate()
        {
            this.Cameras = new HashSet<Camera>();
        }
    
        public int gate_id { get; set; }
        public string gate_name { get; set; }
        public string gate_ip { get; set; }
        public string gate_port { get; set; }
        public Nullable<int> gate_number { get; set; }
    
        public virtual ICollection<Camera> Cameras { get; set; }
    }
}
