//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guard
    {
        public Guard()
        {
            this.Guard1 = new HashSet<Guard>();
        }
    
        public string guard_id { get; set; }
        public string guard_first { get; set; }
        public string guard_middle { get; set; }
        public string guard_last { get; set; }
        public string guard_password { get; set; }
        public string guard_permission { get; set; }
        public Nullable<int> guard_organization { get; set; }
        public Nullable<int> guard_facility { get; set; }
        public string guard_address { get; set; }
        public string guard_city { get; set; }
        public string guard_region { get; set; }
        public string guard_country { get; set; }
        public string guard_phone_1 { get; set; }
        public string guard_phone_2 { get; set; }
        public string guard_email { get; set; }
        public byte[] guard_last_login { get; set; }
        public string guard_manager_id { get; set; }
        public Nullable<System.DateTime> guard_last_password_change { get; set; }
        public Nullable<byte> gate_no { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual ICollection<Guard> Guard1 { get; set; }
        public virtual Guard Guard2 { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
