//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IVISSEntities : DbContext
    {
        public IVISSEntities()
            : base("name=IVISSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Camera> Cameras { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Gate> Gates { get; set; }
        public virtual DbSet<Guard> Guards { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    }
}
