//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public int Id { get; set; }
        public string PortNo { get; set; }
        public string AirWash { get; set; }
        public string Barrier { get; set; }
        public string Lights { get; set; }
        public string Cameras { get; set; }
        public string Relay1 { get; set; }
        public string Relay2 { get; set; }
        public string Relay3 { get; set; }
        public string Relay4 { get; set; }
        public string Relay1Arab { get; set; }
        public string Relay2Arab { get; set; }
        public string Relay3Arab { get; set; }
        public string Relay4Arab { get; set; }
        public string DriverCamIP { get; set; }
        public string LicenseCamIP { get; set; }
        public string SceneCamIP { get; set; }
        public string DriverCamPassword { get; set; }
        public string SceneCamPassword { get; set; }
        public string Relay1Port { get; set; }
        public string Relay2Port { get; set; }
        public string Relay3Port { get; set; }
        public string Relay4Port { get; set; }
        public Nullable<bool> ALPREntryLoop { get; set; }
        public Nullable<bool> ALPRExitLoop { get; set; }
        public Nullable<int> RetentionDays { get; set; }
        public Nullable<int> ComPort { get; set; }
        public string ExitDriverCamIP { get; set; }
        public string ExitLicenseCamIP { get; set; }
        public Nullable<int> DriverRecTimeout { get; set; }
        public string gate_no { get; set; }
        public string IPAddress { get; set; }
        public string ListenPort { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<bool> AIEnabled { get; set; }
        public Nullable<bool> LaserTriggerEnabled { get; set; }
    }
}
