//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int vehicle_license_plate { get; set; }
        public string vehicle_make { get; set; }
        public int vehicle_year { get; set; }
        public string vehicle_model { get; set; }
        public string vehicle_color { get; set; }
        public string vehicle_type { get; set; }
    }
}
