//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVISS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.Visitor1 = new HashSet<Visitor>();
        }
    
        public int visitor_id { get; set; }
        public string visitor_license_plate { get; set; }
        public string visitor_license_plate_arabic { get; set; }
        public string visitor_classification { get; set; }
        public string visitor_authorization { get; set; }
        public string visitor_first { get; set; }
        public string visitor_middle { get; set; }
        public string visitor_last { get; set; }
        public string visitor_address { get; set; }
        public string visitor_city { get; set; }
        public string visitor_region { get; set; }
        public string visitor_country { get; set; }
        public string visitor_phone_1 { get; set; }
        public string visitor_phone_2 { get; set; }
        public string visitor_email { get; set; }
        public string visitor_image { get; set; }
        public Nullable<int> visitor_manager { get; set; }
        public Nullable<int> visitor_organization { get; set; }
        public Nullable<int> visitor_facility { get; set; }
        public Nullable<byte> uploaded { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Visitor> Visitor1 { get; set; }
        public virtual Visitor Visitor2 { get; set; }
    }
}
